[tool.poetry]
name = "pydp"
version = "0.1.0"
description = ""
authors = ["Chinmay Shah <chinmayshah3899@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.5"
jupyter = "*"
pandas = "*"

[tool.poetry.dev-dependencies]
setuptools = "*"
bumpversion = "==0.5.3"
pytest = "*"
black = {version = "==19.10b0",python = "^3.6"}
twine = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
gcovr = "*"
coverage = "*"
mypy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
