name: Tests

on:
  push:
    branches:
    - master, dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Set up submodules
      run: |
        bash ./ext_source_setup.sh
    - name: Install pre-requisites
      run: |
        sudo apt-get update
        bash ./prereqs_linux.sh
        export PATH="$PATH:$HOME/bin"
    - name: Build pydp lib
      run: |
        bash pipenv run ./build_PyDP.sh
    - name: Run tests
      run: |
        pipenv run python setup.py test
    - name: Check test coverage
      run: |
         coverage run --source pydp setup.py test
         coverage report --ignore-errors --fail-under 95 -m
